# Generated by Django 4.2.5 on 2023-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_client_registered_at_alter_item_added_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(blank=True, default='', upload_to='static/images/products/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
